export const ADD_NEW_COURSE='ADD_NEW_COURSE';
export const ENROL_STUDENTS='ENROL_STUDENTS';
export const EDIT_COURSE='EDIT_COURSE';
export const DELETE_COURSE='DELETE_COURSE';
export const FETCH_COURSES='FETCH_COURSES';
export const ADD_NEW_SESSION='ADD_NEW_SESSION';
export const EDIT_SESSION='EDIT_SESSION';
export const DELETE_SESSION='DELETE_SESSION';
export const ADD_NEW_QUESTION='ADD_NEW_QUESTION';
export const EDIT_QUESTION='EDIT_QUESTION';
export const DELETE_QUESTION='DELETE_QUESTION';
export const COMMENT_ON_ANSWER='COMMENT_ON_ANSWER';
export const ADD_IDEAL_SOLUTION='ADD_IDEAL_SOLUTION';
export const CURRENT_COURSE='CURRENT_COURSE';
export const CURRENT_SESSION='CURRENT_SESSION';
export const SUBMIT_ANSWERS='SUBMIT_ANSWERS';
export const PUBLISH_SESSION='PUBLISH_SESSION';






