export const FETCH_ENROLLMENTS='FETCH_ENROLLMENTS';
export const FETCH_SUBMISSIONS='FETCH_SUBMISSIONS';
export const CURRENT_ENROLLMENT='CURRENT_ENROLLMENT';
export const CURRENT_SESSION='CURRENT_SESSION';
export const START_SESSION='START_SESSION';
export const SUBMIT_SESSION='SUBMIT_SESSION';






